   ADD_TEST_SUITE(HamcrestCore_suite)
   ADD_TEST_SUITE(Hamcrest_AnyOf_suite)
   ADD_TEST_SUITE(Hamcrest_AllOf_suite)
   ADD_TEST_SUITE(Hamcrest_Every_suite)
   ADD_TEST_SUITE(Hamcrest_StringContains)
   ADD_TEST_SUITE(Hamcrest_StringStartsWith)
   ADD_TEST_SUITE(Hamcrest_StringEndsWith)
   ADD_TEST_SUITE(Hamcrest_IsArrayWithSize)

   ADD_TEST_SUITE(Hamcrest_IsNear)
   ADD_TEST_SUITE(Hamcrest_IsRelativelyNear)

   ADD_TEST_SUITE(Hamcrest_IsEqual_extended)
