set (CPACK_GENERATOR ZIP)

set (CPACK_PACKAGE_DESCRIPTION_SUMMARY "pFUnit")
set (CPACK_PACKAGE_CONTACT "pFUnit developers <pfunit-developers@list.sourceforge.net>")
set (CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set (CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set (CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")
set (CPACK_INCLUDE_TOPLEVEL_DIRECTORY FALSE)


include (CPack)

